/*
 * Vesktop, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and Vencord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { VesktopSettingsIcon } from "@vencord/types/components";

import SettingsUi from "./components/settings/Settings";
import { DohcordLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

DohcordLogger.log("read if cute :3");
DohcordLogger.log("Dohcord v" + VesktopNative.app.getVersion());

const SettingsPlugin = Vencord.Plugins.plugins
    .Settings as typeof import("@vencord/types/plugins/_core/settings").default;

SettingsPlugin.customEntries.push({
    key: "dohcord",
    title: "Dohcord",
    panelTitle: "Dohcord Settings",
    Component: SettingsUi,
    Icon: VesktopSettingsIcon
});
